/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoOrgRouteImport } from './routes/no-org'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation.$id'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedSettingsTeamRouteImport } from './routes/_authed/settings/team'
import { Route as AuthedSettingsAuditLogRouteImport } from './routes/_authed/settings/audit-log'
import { Route as AuthedDevelopersWebhooksRouteImport } from './routes/_authed/developers/webhooks'
import { Route as AuthedDevelopersJobsRouteImport } from './routes/_authed/developers/jobs'
import { Route as AuthedDevelopersApiKeysRouteImport } from './routes/_authed/developers/api-keys'

const NoOrgRoute = NoOrgRouteImport.update({
  id: '/no-org',
  path: '/no-org',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsTeamRoute = AuthedSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsAuditLogRoute = AuthedSettingsAuditLogRouteImport.update({
  id: '/settings/audit-log',
  path: '/settings/audit-log',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDevelopersWebhooksRoute =
  AuthedDevelopersWebhooksRouteImport.update({
    id: '/developers/webhooks',
    path: '/developers/webhooks',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDevelopersJobsRoute = AuthedDevelopersJobsRouteImport.update({
  id: '/developers/jobs',
  path: '/developers/jobs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDevelopersApiKeysRoute = AuthedDevelopersApiKeysRouteImport.update({
  id: '/developers/api-keys',
  path: '/developers/api-keys',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/no-org': typeof NoOrgRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/developers/api-keys': typeof AuthedDevelopersApiKeysRoute
  '/developers/jobs': typeof AuthedDevelopersJobsRoute
  '/developers/webhooks': typeof AuthedDevelopersWebhooksRoute
  '/settings/audit-log': typeof AuthedSettingsAuditLogRoute
  '/settings/team': typeof AuthedSettingsTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/no-org': typeof NoOrgRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/developers/api-keys': typeof AuthedDevelopersApiKeysRoute
  '/developers/jobs': typeof AuthedDevelopersJobsRoute
  '/developers/webhooks': typeof AuthedDevelopersWebhooksRoute
  '/settings/audit-log': typeof AuthedSettingsAuditLogRoute
  '/settings/team': typeof AuthedSettingsTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/no-org': typeof NoOrgRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/_authed/developers/api-keys': typeof AuthedDevelopersApiKeysRoute
  '/_authed/developers/jobs': typeof AuthedDevelopersJobsRoute
  '/_authed/developers/webhooks': typeof AuthedDevelopersWebhooksRoute
  '/_authed/settings/audit-log': typeof AuthedSettingsAuditLogRoute
  '/_authed/settings/team': typeof AuthedSettingsTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/no-org'
    | '/dashboard'
    | '/accept-invitation/$id'
    | '/developers/api-keys'
    | '/developers/jobs'
    | '/developers/webhooks'
    | '/settings/audit-log'
    | '/settings/team'
    | '/api/auth/$'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/no-org'
    | '/dashboard'
    | '/accept-invitation/$id'
    | '/developers/api-keys'
    | '/developers/jobs'
    | '/developers/webhooks'
    | '/settings/audit-log'
    | '/settings/team'
    | '/api/auth/$'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/no-org'
    | '/_authed/dashboard'
    | '/accept-invitation/$id'
    | '/_authed/developers/api-keys'
    | '/_authed/developers/jobs'
    | '/_authed/developers/webhooks'
    | '/_authed/settings/audit-log'
    | '/_authed/settings/team'
    | '/api/auth/$'
    | '/_authed/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  NoOrgRoute: typeof NoOrgRoute
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/no-org': {
      id: '/no-org'
      path: '/no-org'
      fullPath: '/no-org'
      preLoaderRoute: typeof NoOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings/team': {
      id: '/_authed/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthedSettingsTeamRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/audit-log': {
      id: '/_authed/settings/audit-log'
      path: '/settings/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof AuthedSettingsAuditLogRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/developers/webhooks': {
      id: '/_authed/developers/webhooks'
      path: '/developers/webhooks'
      fullPath: '/developers/webhooks'
      preLoaderRoute: typeof AuthedDevelopersWebhooksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/developers/jobs': {
      id: '/_authed/developers/jobs'
      path: '/developers/jobs'
      fullPath: '/developers/jobs'
      preLoaderRoute: typeof AuthedDevelopersJobsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/developers/api-keys': {
      id: '/_authed/developers/api-keys'
      path: '/developers/api-keys'
      fullPath: '/developers/api-keys'
      preLoaderRoute: typeof AuthedDevelopersApiKeysRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDevelopersApiKeysRoute: typeof AuthedDevelopersApiKeysRoute
  AuthedDevelopersJobsRoute: typeof AuthedDevelopersJobsRoute
  AuthedDevelopersWebhooksRoute: typeof AuthedDevelopersWebhooksRoute
  AuthedSettingsAuditLogRoute: typeof AuthedSettingsAuditLogRoute
  AuthedSettingsTeamRoute: typeof AuthedSettingsTeamRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDevelopersApiKeysRoute: AuthedDevelopersApiKeysRoute,
  AuthedDevelopersJobsRoute: AuthedDevelopersJobsRoute,
  AuthedDevelopersWebhooksRoute: AuthedDevelopersWebhooksRoute,
  AuthedSettingsAuditLogRoute: AuthedSettingsAuditLogRoute,
  AuthedSettingsTeamRoute: AuthedSettingsTeamRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  NoOrgRoute: NoOrgRoute,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
