import type { DMMF } from "@prisma/generator-helper";

import { generateEnums } from "./enums.js";
import { generateManyToManyTables } from "./many-to-many-tables.js";
import { generateProject, type ProjectOptions } from "./project.js";
import { generateRelations } from "./relations.js";
import { generateTables } from "./table.js";

export const autoGeneratedComment = `//// ------------------------------------------------------
//// THIS FILE WAS AUTOMATICALLY GENERATED (DO NOT MODIFY)
//// ------------------------------------------------------`;

export function generateDBMLSchema(
  dmmf: DMMF.Document,
  allowManyToMany: boolean = true,
  mapToDbSchema: boolean = false,
  includeRelationFields: boolean = true,
  projectOptions?: ProjectOptions,
): string {
  const fieldDbNameMaps = new Map<string, string>();

  dmmf.datamodel.models.forEach((model) => {
    model.fields.forEach((field) => {
      fieldDbNameMaps.set(
        `${model.name}.${field.name}`,
        field.dbName || field.name,
      );
    });
  });

  const tables = generateTables(
    dmmf.datamodel.models,
    mapToDbSchema,
    includeRelationFields,
    fieldDbNameMaps,
  );

  const manyToManyTables = allowManyToMany
    ? generateManyToManyTables(dmmf.datamodel.models, mapToDbSchema)
    : [];

  const enums = generateEnums(dmmf.datamodel.enums);

  const refs = generateRelations(
    dmmf.datamodel.models,
    mapToDbSchema,
    fieldDbNameMaps,
  );

  const project = projectOptions ? generateProject(projectOptions) : [];

  return [
    autoGeneratedComment,
    ...project,
    ...tables,
    ...manyToManyTables,
    ...enums,
    ...refs,
  ].join("\n\n");
}
